### ISSUE TITLE
setPinVoltage should take a int16_t for the milliVolts

### ISSUE THREAD

**Issue by elmicha** [Crypter/QC3Client#1]
Hi,

thank you for your great library, it works after a bit of messing with it.
At first the examples didn't compile because there was an extra closing parenthese in the lines with println:

      Serial.println(QC3Client.setMillivolts(5000)) / 1000.0); //USB 5.0V

should be
 
      Serial.println(QC3Client.setMillivolts(5000) / 1000.0); //USB 5.0V

Then it still didn't work, until I saw these warnings:

```
In file included from /home/elmicha/Arduino/sketches/Zeug/QC3_demo/QC3_demo.ino:1:0:
/home/elmicha/Arduino/libraries/QC3Client/src/QC3Client.h: In member function 'uint8_t QC3ClientClass::begin(uint8_t, uint8_t)':
/home/elmicha/Arduino/libraries/QC3Client/src/QC3Client.h:73:32: warning: overflow in implicit constant conversion [-Woverflow]
           setPinVoltage(dp, 600);
                                ^
```
I changed the line

    void setPinVoltage(QC3Pins pin, int8_t milliVolts) {

to

    void setPinVoltage(QC3Pins pin, int16_t milliVolts) {

and now it works! Thank you!

Best regards...
  Michael

**Comment by Crypter** [comment]
I must've got it wrong while refactoring. All fixed now, thanks for reporting!
